version: '3.7'

services:
  postgres:
    image: postgres:9.6.16
    container_name: postgres-notification-service
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      POSTGRES_DOCKER: postgres:5432
#    depends_on:
#      - postgres
#    ports:
#      - "9091:9091"