definitions:
  model.HTTPError400:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  model.HTTPError500:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Internal Server Error
        type: string
    type: object
info:
  contact:
    email: ahmad.hassan@gmail.com
    name: Dr Ahmad Hassan
    url: https://www.linkedin.com/in/ahmadhassan
  description: This is an api for notification service.
  termsOfService: http://swagger.io/terms/
  title: Notification API
  version: "1.0"
paths:
  /notification/subscribe:
    post:
      consumes:
        - application/json
      description: The subscription endpoint to subscribe to the notification url.
      parameters:
        - description: The notification url
          in: query
          name: url
          required: true
          type: string
        - description: The id of the customer
          in: query
          name: customerId
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "201":
          description: "The subscription has been created."
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError500'
      summary: Test the notification
      tags:
        - Notification
  /notification/activate:
    post:
      consumes:
        - application/json
      description: Activate the particular notification URL
      produces:
        - application/json
      parameters:
        - description: The notification url
          in: query
          name: url
          required: true
          type: string
        - description: The id of the customer
          in: query
          name: customerId
          required: true
          type: integer
      responses:
        "201":
          description: "The resouce has been activated."
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError500'
      summary: Activate the notification
      tags:
        - Notification
  /notification/test:
    post:
      consumes:
        - application/json
      description: The endpoint for testing the notifications.
      produces:
        - application/json
      parameters:
        - description: The notification url
          in: query
          name: url
          required: true
          type: string
        - description: The id of the customer
          in: query
          name: customerId
          required: true
          type: integer
        - in: "body"
          name: "body"
          description: "The payload"
          required: true
          schema:
            type: "object"
            required:
              - "name"
              - "photoUrls"
            properties:
              messageId:
                type: "string"
                example: 511c366e-8b0d-458f-9579-91a1096dc120
              customerKey:
                type: "string"
                example: "346376e9-db72-423b-906f-d4bcf1198df5"
              payment:
                type: "integer"
                example: 1234
      responses:
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError500'
      summary: Test the notification
      tags:
        - Notification
swagger: "2.0"
